version: "3.8"
services:
  nginx:
    image: nginx
    restart: unless-stopped
    hostname: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "8081:8081"
      - "443:443"
    volumes:
      - /var/djnext:/app/static
    depends_on:
      - node
      - server

  server:
    image: django
    restart: unless-stopped
    hostname: server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    volumes:
      - /var/djnext:/app
    depends_on:
      - postgres
      - node

  node:
    image: node
    restart: unless-stopped
    hostname: nextjs
    build:
      context: .
      dockerfile: ./client/Dockerfile
      args:
        UID: ${UID:-1000}
    user: '${UID:-1000}:${GID:-1000}'
    env_file:
      - .env
    volumes:
      - /var/djnext:/var/djnext

  postgres:
    image: postgres:14.2
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - /var/postgres/data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=gobiloc
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
