version: "3.4"

services:
  # NGINX proxy
  nginx:
    image: nginx
    restart: unless-stopped
    hostname: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "8081:8081"
      - "443:443"
    volumes:
      - /var/djnext:/media
    links:
      - server:server
    depends_on:
      - server
      - node

  # Django server
  server:
    image: django
    restart: unless-stopped
    hostname: server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    volumes:
      - /var/djnext:/var/djnext
    links:
      - node:node
      - postgres:postgres
    depends_on:
      - postgres
      - node

  # Next.js server
  node:
    image: node
    restart: unless-stopped
    hostname: nextjs
    build:
      context: .
      dockerfile: ./client/Dockerfile
      args:
        UID: ${UID:-1000}
    user: '${UID:-1000}:${GID:-1000}'
    env_file:
      - .env.local
    volumes:
      - /var/djnext:/var/djnext

  # Postgres database
  postgres:
    image: postgres:14.2
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - /var/postgres/data:/var/postgres/data
    env_file:
      - .env.local