# Generated by Django 5.0.3 on 2024-10-20 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_budget_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='flat_share',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='api.flatshare'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todo',
            name='flat_share',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='api.flatshare'),
        ),
        migrations.AlterField(
            model_name='user',
            name='flat_share',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.flatshare'),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flat_share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='api.flatshare')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
