# Generated by Django 5.0.3 on 2024-10-30 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_budget_flat_share_alter_expense_user_and_more'),
        ('api', '0006_expense_date_alter_budget_flat_share_and_more'),
    ]

    operations = [
    ]
