# Generated by Django 5.0.3 on 2024-10-30 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_merge_20241030_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='flat_share',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.flatshare'),
        ),
    ]
