# The heart of the pre-commit framework is the .pre-commit-config.yaml file.
# This file defines the hooks you want to run and where to find them.
# Hooks are specified as Git repositories, and each hook is associated with a command or script to execute.

exclude: .*migrations\/.*

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        files: ^server/
      - id: end-of-file-fixer
        files: ^server/
      - id: trailing-whitespace
        files: ^server/
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3.11
        files: ^server/
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        files: ^server/
