name: Biome Linter # Front side

on:
  push:
    branches: [ "main" ]
    paths:
      - "client/api/**"  # When changes on the frontend
  pull_request:
    branches: [ "main" ]
    paths:
      - "client/api/**"

jobs:
  biome:
    name: Run biome scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Biome CLI
        uses: biomejs/setup-biome@v2

      - name: Run Biome
        run: biome ci ./client/app
