name: Django CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "server/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "server/**"


jobs:
  build_server_back:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: gobilocTest
          POSTGRES_USER: postgresCI
          POSTGRES_PASSWORD: postgresCI
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=5

    env:
      
      DJANGO_SETTINGS_MODULE: gobiloc.settings
      DB_NAME: gobilocTest
      DB_USER: postgresCI
      DB_PASSWORD: postgresCI
      DB_HOST: localhost
      DB_PORT: "5432"
      DATABASE_URL: postgres://postgresCI:postgresCI@localhost:5432/gobilocTest
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: 'True'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r server/requirements.txt

      - name: Run migrations
        run: |
          python server/manage.py migrate
