name: Pylint # For python

on:
  push:
    branches: [ "main" ]
    paths:
      - "server/**"  # Only changes on the server side
  pull_request:
    branches: [ "main" ]
    paths:
      - "server/**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r server/requirements.txt
          pip install pylint

      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files 'server/**/*.py')  # Analyse uniquement les fichiers Python dans ./server
