name: Ruff # Lint for Backend

on:
  push:
    branches: [ "main" ]
    paths:
      - "server/**"  # Only for changes on backend
  pull_request:
    branches: [ "main" ]
    paths:
      - "server/**"
      - ".github/**"
  workflow_dispatch: 

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Ruff
        uses: chartboost/ruff-action@v1
